//! `move-bindgen init` — write a starter `move-bindgen.toml` next to the
//! user's Move sources so `install`/`generate` work without further
//! schema-learning.
//!
//! One template, always workspace-mode. Workspace-with-one-package is a
//! valid degenerate shape and keeps the schema consistent across
//! single- and multi-package projects.

use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

use crate::config::{config_path_in, DEFAULT_RUNTIME_GIT_URL};

/// Decide an output crate-name from a directory's basename.
/// Lowercases, swaps `_` → `-`, and appends `-rs` (skipped when the
/// basename already ends in `-rs` to avoid `foo-rs-rs`).
/// Canonicalises first so that `.` and `./` resolve to the cwd's
/// actual basename instead of falling through to the literal `.`.
/// Falls back to `bindings-rs` only when no basename can be extracted
/// at all (e.g. dir is `/`).
pub fn default_output_name_from_dir(dir: &Path) -> String {
    let canonical = std::fs::canonicalize(dir).unwrap_or_else(|_| dir.to_path_buf());
    let stem = canonical
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("bindings");
    let kebab: String = stem
        .chars()
        .map(|c| {
            if c == '_' {
                '-'
            } else {
                c.to_ascii_lowercase()
            }
        })
        .collect();
    if kebab.ends_with("-rs") {
        kebab
    } else {
        format!("{kebab}-rs")
    }
}

/// Render the starter template. `output_name` becomes the crate-name
/// for the generated workspace; other knobs use sensible defaults
/// users can edit afterwards.
pub fn render_starter(output_name: &str) -> String {
    let docs_url = DEFAULT_RUNTIME_GIT_URL.trim_end_matches(".git");
    format!(
        r#"# move-bindgen.toml — generated by `move-bindgen init`.
# Docs: {docs_url}

# Override the default ["Iota", "MoveStdlib"] so the Iota framework and
# Move stdlib generate as peer crates. Without this, codegen errors on
# any reference to Iota types beyond the runtime's well-known set
# (UID, ID, Option, String) — e.g. `iota::coin::Coin`,
# `iota::linked_table::LinkedTable`. Drop this line if your packages
# only touch the well-known runtime types.
framework_packages = []

[output]
format  = "workspace"
name    = "{output_name}"
runtime = {{ git = "{git_url}" }}

# List your top-level Move packages here. Auto-discovery walks each
# package's [dependencies] and pulls in transitives automatically —
# only the entry points you actually want bindings for need to be listed.
#
# Local-source example:
# [packages.<id>]
# path = "packages/<your-package>"
#
# Git-source example:
# [packages.<id>]
# git    = "https://github.com/<owner>/<repo>.git"
# rev    = "<commit-or-tag>"
# subdir = "<sub-path-in-repo>"
"#,
        git_url = DEFAULT_RUNTIME_GIT_URL,
    )
}

/// Options for [`run`]. All knobs the CLI exposes.
#[derive(Debug, Clone, Default)]
pub struct InitOptions {
    /// Override the auto-derived crate name (default: kebab-cased
    /// directory basename + `-rs`).
    pub name: Option<String>,
    /// Overwrite an existing `move-bindgen.toml`. Off by default to
    /// keep `init` a non-destructive verb; the CLI exposes `--force`.
    pub force: bool,
}

/// Write a starter `move-bindgen.toml` into `dir`. Errors if a config
/// already exists there unless `opts.force` is set.
pub fn run(dir: &Path, opts: &InitOptions) -> Result<PathBuf> {
    let path = config_path_in(dir);
    if path.exists() && !opts.force {
        bail!(
            "{} already exists — pass --force to overwrite",
            path.display()
        );
    }
    let output_name = opts
        .name
        .clone()
        .unwrap_or_else(|| default_output_name_from_dir(dir));
    let body = render_starter(&output_name);
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_name_kebabs_and_lowercases() {
        // Use existing dirs so canonicalize resolves; otherwise the
        // fallback path uses the input verbatim and the basename of
        // a non-existent "MyProject" is "MyProject" → still kebabbed.
        assert_eq!(
            default_output_name_from_dir(Path::new("MyProject")),
            "myproject-rs"
        );
        assert_eq!(
            default_output_name_from_dir(Path::new("foo_bar")),
            "foo-bar-rs"
        );
        assert_eq!(default_output_name_from_dir(Path::new("/")), "bindings-rs");
    }

    #[test]
    fn default_name_skips_rs_doubling() {
        // A folder already named `<x>-rs` should NOT become `<x>-rs-rs`.
        assert_eq!(
            default_output_name_from_dir(Path::new("exchange-rs")),
            "exchange-rs"
        );
        assert_eq!(
            default_output_name_from_dir(Path::new("Exchange_RS")),
            "exchange-rs"
        );
    }

    #[test]
    fn default_name_resolves_dot_to_cwd_basename() {
        // Make a temp dir, cd into it, and check that `.` produces a
        // name based on the temp dir's basename rather than
        // "bindings-rs". Restore cwd so we don't pollute the suite.
        let dir =
            std::env::temp_dir().join(format!("move-bindgen-init-dot-{}", std::process::id()));
        if dir.exists() {
            std::fs::remove_dir_all(&dir).unwrap();
        }
        std::fs::create_dir_all(&dir).unwrap();
        let saved = std::env::current_dir().unwrap();
        std::env::set_current_dir(&dir).unwrap();

        let name = default_output_name_from_dir(Path::new("."));

        std::env::set_current_dir(saved).unwrap();
        std::fs::remove_dir_all(&dir).unwrap();

        assert!(
            name.ends_with("-rs") && !name.starts_with("bindings"),
            "expected name based on cwd basename, got {name}",
        );
    }

    #[test]
    fn template_is_valid_toml_with_runtime() {
        let body = render_starter("counter-rs");
        let v: toml::Value = toml::from_str(&body).expect("template parses as TOML");
        assert_eq!(
            v["output"]["format"].as_str(),
            Some("workspace"),
            "template defaults to workspace mode"
        );
        assert_eq!(v["output"]["name"].as_str(), Some("counter-rs"));
        assert_eq!(
            v["output"]["runtime"]["git"].as_str(),
            Some(DEFAULT_RUNTIME_GIT_URL),
            "runtime points at the public git default"
        );
        assert_eq!(
            v["framework_packages"].as_array().map(Vec::len),
            Some(0),
            "starter sets framework_packages = [] so Iota framework generates as peer crates"
        );
    }

    #[test]
    fn run_refuses_to_overwrite_without_force() {
        let dir = std::env::temp_dir().join(format!("move-bindgen-init-{}", std::process::id()));
        if dir.exists() {
            std::fs::remove_dir_all(&dir).unwrap();
        }
        std::fs::create_dir_all(&dir).unwrap();

        let written = run(&dir, &InitOptions::default()).unwrap();
        assert!(written.is_file(), "first run wrote the file");

        let err = run(&dir, &InitOptions::default()).unwrap_err();
        assert!(
            format!("{err}").contains("--force"),
            "second run errors with the --force hint: {err}",
        );
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn run_overwrites_with_force() {
        let dir =
            std::env::temp_dir().join(format!("move-bindgen-init-force-{}", std::process::id()));
        if dir.exists() {
            std::fs::remove_dir_all(&dir).unwrap();
        }
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("move-bindgen.toml"), "stale = true\n").unwrap();

        let written = run(
            &dir,
            &InitOptions {
                force: true,
                ..Default::default()
            },
        )
        .unwrap();
        let body = std::fs::read_to_string(&written).unwrap();
        assert!(
            body.contains("[output]"),
            "force overwrote with the starter template",
        );
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn run_honors_name_override() {
        let dir =
            std::env::temp_dir().join(format!("move-bindgen-init-name-{}", std::process::id()));
        if dir.exists() {
            std::fs::remove_dir_all(&dir).unwrap();
        }
        std::fs::create_dir_all(&dir).unwrap();
        let written = run(
            &dir,
            &InitOptions {
                name: Some("my-bindings".into()),
                ..Default::default()
            },
        )
        .unwrap();
        let body = std::fs::read_to_string(&written).unwrap();
        assert!(
            body.contains("name    = \"my-bindings\""),
            "explicit --name wins over the dir-basename default",
        );
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
