//! Codegen for the `Package::deployer(Network::...)` surface and the
//! per-network `bytecode/<name>.rs` data files.
//!
//! Driven by [`NetworkArtifact`] entries on `Bindings`. Empty input ⇒
//! no deploy API is emitted (silent skip), so existing configs without
//! `[publish]` see no change in output.

use anyhow::{Context, Result};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use super::{inner_doc, outer_doc};
use crate::ir::NetworkArtifact;

/// All files + lib.rs fragments produced by deploy codegen for one
/// generated crate. Empty when no networks were configured.
#[derive(Debug, Default)]
pub(super) struct DeployCodegen {
    /// `(file_name, source)` pairs — `bytecode/mod.rs` plus one
    /// `bytecode/<network>.rs` per configured network. Empty when no
    /// networks were configured.
    pub files: Vec<(String, String)>,
    /// Token stream to inject into `lib.rs`. Holds the `Network` enum,
    /// `Package::deployer(...)` impl block, and `pub mod bytecode`
    /// declaration. Empty when no networks were configured.
    pub lib_tokens: TokenStream,
}

/// Build the deploy-codegen output. `Ok(DeployCodegen::default())` is
/// returned (and is what the caller wants) when `artifacts` is empty.
pub(super) fn build(artifacts: &[NetworkArtifact]) -> Result<DeployCodegen> {
    if artifacts.is_empty() {
        return Ok(DeployCodegen::default());
    }

    let mut files = Vec::with_capacity(artifacts.len() + 1);
    let mut mod_decls = Vec::with_capacity(artifacts.len());
    let mut variants = Vec::with_capacity(artifacts.len());
    let mut match_arms = Vec::with_capacity(artifacts.len());

    for net in artifacts {
        let file_basename = sanitize_module_name(&net.network);
        let file_ident = format_ident!("{}", file_basename);
        let variant_ident = format_ident!("{}", to_pascal_case(&net.network));

        let body = render_bytecode_file(net).with_context(|| {
            format!(
                "rendering bytecode/{file_basename}.rs for network '{}'",
                net.network
            )
        })?;
        files.push((format!("bytecode/{file_basename}.rs"), body));
        mod_decls.push(quote! { pub mod #file_ident; });

        let variant_doc = format!("Configured for `{}`.", net.network);
        variants.push(quote! {
            #[doc = #variant_doc]
            #variant_ident
        });
        match_arms.push(quote! {
            Network::#variant_ident => (
                bytecode::#file_ident::MODULES,
                bytecode::#file_ident::DEPENDENCIES,
                bytecode::#file_ident::DIGEST,
                bytecode::#file_ident::DEP_LABELS,
            )
        });
    }

    let bytecode_mod = render_bytecode_mod(&mod_decls)?;
    files.push(("bytecode/mod.rs".to_string(), bytecode_mod));

    let lib_tokens = quote! {
        pub mod bytecode;

        /// Networks this package's bytecode was compiled for. Each
        /// variant points at a `bytecode/<name>.rs` table holding the
        /// modules, deps, and digest produced at codegen time.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum Network {
            #( #variants ),*
        }

        impl Package {
            /// Get a deployer for this package on `network`. Returns a
            /// chainable builder — attach a client/signer and call
            /// `.execute()` to publish.
            ///
            /// ```ignore
            /// let result = Package::deployer(Network::Testnet)
            ///     .with_client(client)
            ///     .with_signer(signer)
            ///     .with_auto_gas()
            ///     .execute()
            ///     .await?;
            /// ```
            pub fn deployer(network: Network) -> move_bindgen_runtime::PackageDeployer {
                let (modules, dependencies, digest, dep_labels) = match network {
                    #( #match_arms ),*
                };
                move_bindgen_runtime::PackageDeployer::new(
                    modules,
                    dependencies,
                    digest,
                    dep_labels,
                )
            }
        }
    };

    Ok(DeployCodegen { files, lib_tokens })
}

/// Render one network's bytecode table as a standalone module file.
fn render_bytecode_file(net: &NetworkArtifact) -> Result<String> {
    let module_literals = net.modules.iter().map(|m| byte_slice_literal(m));
    let dep_literals = net.dependencies.iter().map(address_literal);
    let digest_literals = net.digest.iter().map(|b| quote! { #b });
    let label_literals = net.dep_labels.iter().map(|(addr, name)| {
        let addr_tokens = address_literal(addr);
        let name_lit = name.as_str();
        quote! { (#addr_tokens, #name_lit) }
    });

    let file_doc = format!(
        "@generated by move-bindgen — do not edit by hand.\n\n\
         Publishable bytecode + dep set captured at codegen time for the\n\
         `{}` network.",
        net.network,
    );
    let modules_doc = format!(
        "Serialized Move modules ({} total), in dependency order.",
        net.modules.len(),
    );
    let deps_doc = format!(
        "On-chain addresses of transitive dependencies ({} total).",
        net.dependencies.len(),
    );
    let labels_doc = format!(
        "Workspace-synthetic dep labels ({} total) — `(synthetic_address, \
         move_package_name)` pairs. Pass each name to \
         `PackageDeployer::resolve_dep(name, real_addr)` to substitute \
         the real on-chain id at publish time. Empty when the package \
         has no workspace-internal deps.",
        net.dep_labels.len(),
    );

    let file_doc_attr = inner_doc(&file_doc);
    let modules_doc_attr = outer_doc(&modules_doc);
    let deps_doc_attr = outer_doc(&deps_doc);
    let labels_doc_attr = outer_doc(&labels_doc);

    let tokens = quote! {
        #file_doc_attr
        #![allow(missing_docs)]

        #modules_doc_attr
        pub static MODULES: &[&[u8]] = &[
            #( #module_literals ),*
        ];

        #deps_doc_attr
        pub static DEPENDENCIES: &[move_bindgen_runtime::Address] = &[
            #( #dep_literals ),*
        ];

        /// Package digest as reported to the chain.
        pub static DIGEST: [u8; 32] = [
            #( #digest_literals ),*
        ];

        #labels_doc_attr
        pub static DEP_LABELS: &[(move_bindgen_runtime::Address, &str)] = &[
            #( #label_literals ),*
        ];
    };
    let file: syn::File =
        syn::parse2(tokens).context("parsing generated bytecode TokenStream as syn::File")?;
    Ok(prettyplease::unparse(&file))
}

/// Render an `Address::new([…])` literal from a 32-byte address.
fn address_literal(addr: &move_core_types::account_address::AccountAddress) -> TokenStream {
    let bytes = addr.into_bytes();
    let byte_literals = bytes.iter().map(|b| quote! { #b });
    quote! { move_bindgen_runtime::Address::new([ #( #byte_literals ),* ]) }
}

fn render_bytecode_mod(mod_decls: &[TokenStream]) -> Result<String> {
    let header = inner_doc(
        "@generated by move-bindgen — do not edit by hand.\n\n\
         Per-network publishable bytecode tables. One submodule per\n\
         `[publish.networks]` entry in the `move-bindgen.toml`.",
    );
    let tokens = quote! {
        #header
        #( #mod_decls )*
    };
    let file: syn::File = syn::parse2(tokens)
        .context("parsing generated bytecode/mod.rs TokenStream as syn::File")?;
    Ok(prettyplease::unparse(&file))
}

/// Emit a byte-slice literal. Returns `&[0x12u8, 0x34, ...]`. Empty
/// slices come out as `&[]`.
fn byte_slice_literal(bytes: &[u8]) -> TokenStream {
    let lits = bytes.iter().map(|b| quote! { #b });
    quote! { &[ #( #lits ),* ] }
}

/// Convert a kebab/snake-case network name into PascalCase for a Rust
/// enum variant. `testnet` → `Testnet`, `local-dev` → `LocalDev`,
/// `my_net2` → `MyNet2`.
fn to_pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut up = true;
    for c in s.chars() {
        if c == '-' || c == '_' {
            up = true;
            continue;
        }
        if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Translate a network name into a valid Rust module identifier: keep
/// letters/digits/underscore, replace `-` with `_`. The config schema
/// already restricts names to `[A-Za-z0-9_-]+`, so no other characters
/// need handling.
fn sanitize_module_name(s: &str) -> String {
    s.chars().map(|c| if c == '-' { '_' } else { c }).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use move_core_types::account_address::AccountAddress;

    #[test]
    fn empty_artifacts_yields_no_files_or_tokens() {
        let out = build(&[]).unwrap();
        assert!(out.files.is_empty());
        assert!(out.lib_tokens.is_empty());
    }

    #[test]
    fn one_network_emits_two_files() {
        let artifact = NetworkArtifact {
            network: "testnet".into(),
            modules: vec![vec![0x12, 0x34], vec![0xff]],
            dependencies: vec![AccountAddress::from_hex_literal("0x2").unwrap()],
            digest: [7u8; 32],
            dep_labels: Vec::new(),
        };
        let out = build(&[artifact]).unwrap();
        let names: Vec<&str> = out.files.iter().map(|(n, _)| n.as_str()).collect();
        assert!(
            names.contains(&"bytecode/testnet.rs"),
            "missing testnet file in: {names:?}"
        );
        assert!(
            names.contains(&"bytecode/mod.rs"),
            "missing bytecode/mod.rs in: {names:?}"
        );

        let testnet = out
            .files
            .iter()
            .find_map(|(n, b)| (n == "bytecode/testnet.rs").then_some(b.as_str()))
            .unwrap();
        assert!(testnet.contains("pub static MODULES"));
        assert!(testnet.contains("pub static DEPENDENCIES"));
        assert!(testnet.contains("pub static DIGEST"));
    }

    #[test]
    fn kebab_network_name_becomes_pascal_variant_and_snake_file() {
        let artifact = NetworkArtifact {
            network: "local-dev".into(),
            modules: vec![],
            dependencies: vec![],
            digest: [0u8; 32],
            dep_labels: Vec::new(),
        };
        let out = build(&[artifact]).unwrap();
        assert!(out.files.iter().any(|(n, _)| n == "bytecode/local_dev.rs"));
        let lib = out.lib_tokens.to_string();
        assert!(lib.contains("LocalDev"), "got: {lib}");
        assert!(lib.contains("local_dev"), "got: {lib}");
    }

    #[test]
    fn deployer_method_uses_runtime_path() {
        let artifact = NetworkArtifact {
            network: "testnet".into(),
            modules: vec![],
            dependencies: vec![],
            digest: [0u8; 32],
            dep_labels: Vec::new(),
        };
        let out = build(&[artifact]).unwrap();
        let lib = out.lib_tokens.to_string();
        assert!(
            lib.contains("move_bindgen_runtime :: PackageDeployer")
                || lib.contains("move_bindgen_runtime::PackageDeployer"),
            "Package::deployer should call into the runtime's PackageDeployer, got: {lib}"
        );
    }
}
