//! Bindings → Rust source.

mod datatype;
mod ty;

use anyhow::{Context, Result};
use move_core_types::account_address::AccountAddress;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::Bindings;

use ty::TypeCtx;

/// Render `bindings` to a single Rust source file.
pub fn generate(bindings: &Bindings) -> Result<String> {
    let package_addr = bindings
        .published_at
        .or_else(|| bindings.modules.first().map(|m| m.id.address))
        .unwrap_or(AccountAddress::ZERO);

    let mut modules = TokenStream::new();
    for m in &bindings.modules {
        let mod_ident = format_ident!("{}", m.id.name.as_str());
        let ctx = TypeCtx {
            package_addr,
            current_module: &m.id.name,
        };
        let datatypes = datatype::emit_datatypes(m, &ctx)
            .with_context(|| format!("codegen for module {}", m.id.name))?;
        if datatypes.is_empty() {
            continue;
        }
        modules.extend(quote! {
            pub mod #mod_ident {
                #datatypes
            }
        });
    }

    let pkg_addr_bytes = package_addr.into_bytes();
    let pkg_addr_lit = pkg_addr_bytes
        .iter()
        .map(|b| quote!(#b))
        .collect::<Vec<_>>();

    let header = quote! {
        // @generated by move-bindgen — do not edit by hand.
        #![allow(unused_imports, non_snake_case, clippy::too_many_arguments)]

        /// Address the package was generated against.
        pub const PACKAGE_ID: ::move_bindgen_runtime::AccountAddress =
            ::move_bindgen_runtime::AccountAddress::new([ #( #pkg_addr_lit ),* ]);

        #modules
    };

    let file: syn::File =
        syn::parse2(header).context("parsing generated TokenStream as syn::File")?;
    Ok(prettyplease::unparse(&file))
}
