//! Bindings → a complete generated Rust crate.

mod datatype;
mod ty;

use anyhow::{Context, Result};
use move_core_types::account_address::AccountAddress;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::Bindings;

use ty::TypeCtx;

/// Files of a generated Rust crate, ready to be written to disk.
#[derive(Debug)]
pub struct GeneratedCrate {
    /// Crate name (e.g. `counter-rs`).
    pub crate_name: String,
    /// Original Move package name (e.g. `counter`).
    pub package_name: String,
    /// `Cargo.toml` source.
    pub cargo_toml: String,
    /// `src/lib.rs` source.
    pub lib_rs: String,
    /// `(file_name, source)` pairs for `src/<file_name>` — one per Move
    /// module that has datatypes.
    pub module_files: Vec<(String, String)>,
}

/// Knobs for `generate`.
#[derive(Debug, Clone)]
pub struct GenerateOptions {
    /// Path to use for the `move-bindgen-runtime` dependency in the generated
    /// `Cargo.toml`. Default points at the in-tree runtime crate; users
    /// generating outside this workspace should override.
    pub runtime_path: String,
}

impl Default for GenerateOptions {
    fn default() -> Self {
        Self {
            runtime_path: "../../crates/move-bindgen-runtime".into(),
        }
    }
}

pub fn generate(bindings: &Bindings, opts: &GenerateOptions) -> Result<GeneratedCrate> {
    let package_addr = bindings
        .published_at
        .or_else(|| bindings.modules.first().map(|m| m.id.address))
        .unwrap_or(AccountAddress::ZERO);

    let crate_name = format!("{}-rs", bindings.package_name);

    // Per-module sources. Skip modules with no datatypes (e.g. pure-function
    // modules) — they'd produce empty .rs files.
    let mut module_files = Vec::new();
    let mut module_names = Vec::new();
    for m in &bindings.modules {
        let ctx = TypeCtx {
            package_addr,
            current_module: &m.id.name,
        };
        let body = datatype::emit_datatypes(m, &ctx)
            .with_context(|| format!("codegen for module {}", m.id.name))?;
        if body.is_empty() {
            continue;
        }
        let module_source = render_module(body)?;
        let mod_name = m.id.name.as_str().to_string();
        module_files.push((format!("{mod_name}.rs"), module_source));
        module_names.push(mod_name);
    }

    let lib_rs = render_lib_rs(&module_names, package_addr)?;
    let cargo_toml = render_cargo_toml(&crate_name, &bindings.package_name, &opts.runtime_path);

    Ok(GeneratedCrate {
        crate_name,
        package_name: bindings.package_name.clone(),
        cargo_toml,
        lib_rs,
        module_files,
    })
}

fn render_module(body: TokenStream) -> Result<String> {
    let header = quote! {
        // @generated by move-bindgen — do not edit by hand.
        #![allow(unused_imports, non_snake_case)]

        use move_bindgen_runtime::*;
        use serde::{Deserialize, Serialize};
        use std::marker::PhantomData;

        #body
    };
    let file: syn::File =
        syn::parse2(header).context("parsing generated module TokenStream as syn::File")?;
    Ok(prettyplease::unparse(&file))
}

fn render_lib_rs(modules: &[String], package_addr: AccountAddress) -> Result<String> {
    let mod_decls = modules.iter().map(|n| {
        let ident = format_ident!("{}", n);
        quote! { pub mod #ident; }
    });
    let bytes = package_addr.into_bytes();
    let byte_lits = bytes.iter().map(|b| quote!(#b));

    let lib = quote! {
        // @generated by move-bindgen — do not edit by hand.
        #![allow(unused_imports, non_snake_case, clippy::too_many_arguments)]

        use move_bindgen_runtime::AccountAddress;

        #( #mod_decls )*

        /// Address the package was generated against.
        pub const PACKAGE_ID: AccountAddress = AccountAddress::new([ #( #byte_lits ),* ]);
    };
    let file: syn::File =
        syn::parse2(lib).context("parsing generated lib.rs TokenStream as syn::File")?;
    Ok(prettyplease::unparse(&file))
}

fn render_cargo_toml(crate_name: &str, package_name: &str, runtime_path: &str) -> String {
    format!(
        "# @generated by move-bindgen — regenerate with `move-bindgen generate`.\n\
         \n\
         [package]\n\
         name = \"{crate_name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\
         description = \"Generated bindings for the `{package_name}` Move package.\"\n\
         \n\
         [dependencies]\n\
         move-bindgen-runtime = {{ path = \"{runtime_path}\" }}\n\
         serde = {{ version = \"1\", features = [\"derive\"] }}\n\
         \n\
         # Detach this crate from any parent workspace it might be generated inside.\n\
         [workspace]\n",
    )
}
