//! Bindings → a complete generated Rust crate.

mod constant;
mod datatype;
mod function;
mod ty;

use anyhow::{Context, Result};
use move_core_types::account_address::AccountAddress;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::Bindings;

use ty::TypeCtx;

/// Emit `#[doc = "..."]` attributes — one per line of `s` so prettyplease
/// renders them as `///` lines instead of folding into a `/** ... */` block.
pub(crate) fn outer_doc(s: &str) -> TokenStream {
    let mut out = TokenStream::new();
    for line in s.split('\n') {
        out.extend(quote!(#[doc = #line]));
    }
    out
}

/// Inner-attribute (`#![doc = "..."]`) flavour for module-level docs.
pub(crate) fn inner_doc(s: &str) -> TokenStream {
    let mut out = TokenStream::new();
    for line in s.split('\n') {
        out.extend(quote!(#![doc = #line]));
    }
    out
}

/// Files of a generated Rust crate, ready to be written to disk.
#[derive(Debug)]
pub struct GeneratedCrate {
    /// Crate name (e.g. `counter-rs`).
    pub crate_name: String,
    /// Original Move package name (e.g. `counter`).
    pub package_name: String,
    /// `Cargo.toml` source.
    pub cargo_toml: String,
    /// `src/lib.rs` source.
    pub lib_rs: String,
    /// `(file_name, source)` pairs for `src/<file_name>` — one per Move
    /// module that has datatypes.
    pub module_files: Vec<(String, String)>,
}

/// Knobs for `generate`.
#[derive(Debug, Clone)]
pub struct GenerateOptions {
    /// How the generated `Cargo.toml` should reference
    /// `move-bindgen-runtime`. For path specs, the caller is responsible
    /// for handing in a path that's already relative to the output
    /// directory (e.g. by re-relativizing a config-relative path).
    pub runtime: crate::config::RuntimeSpec,
}

impl Default for GenerateOptions {
    fn default() -> Self {
        Self {
            runtime: crate::config::RuntimeSpec::Path(std::path::PathBuf::from(
                "../../crates/move-bindgen-runtime",
            )),
        }
    }
}

pub fn generate(bindings: &Bindings, opts: &GenerateOptions) -> Result<GeneratedCrate> {
    let package_addr = bindings
        .published_at
        .or_else(|| bindings.modules.first().map(|m| m.id.address))
        .unwrap_or(AccountAddress::ZERO);

    let crate_name = format!("{}-rs", bindings.package_name);

    // Per-module sources. Skip modules with no items to emit — they'd
    // produce empty .rs files.
    let mut module_files = Vec::new();
    let mut module_names = Vec::new();
    for (i, m) in bindings.modules.iter().enumerate() {
        let ctx = TypeCtx {
            package_addr,
            current_module: &m.id.name,
            docs: &bindings.docs,
        };
        let names = bindings
            .constant_names
            .get(i)
            .map(|v| v.as_slice())
            .unwrap_or(&[]);
        let mut body = constant::emit_constants(&m.constants, &names.to_vec(), &ctx)
            .with_context(|| format!("constant codegen for module {}", m.id.name))?;
        body.extend(
            datatype::emit_datatypes(m, &ctx)
                .with_context(|| format!("datatype codegen for module {}", m.id.name))?,
        );
        body.extend(
            function::emit_functions(m, &ctx)
                .with_context(|| format!("function codegen for module {}", m.id.name))?,
        );
        if body.is_empty() {
            continue;
        }
        let module_doc = bindings.docs.module(m.id.name.as_str());
        let module_source = render_module(body, module_doc)?;
        let mod_name = m.id.name.as_str().to_string();
        module_files.push((format!("{mod_name}.rs"), module_source));
        module_names.push(mod_name);
    }

    let lib_rs = render_lib_rs(&module_names, package_addr)?;
    let cargo_toml = render_cargo_toml(&crate_name, &bindings.package_name, &opts.runtime);

    Ok(GeneratedCrate {
        crate_name,
        package_name: bindings.package_name.clone(),
        cargo_toml,
        lib_rs,
        module_files,
    })
}

fn render_module(body: TokenStream, module_doc: Option<&str>) -> Result<String> {
    let doc_attr = module_doc.map(inner_doc).unwrap_or_default();
    let header = quote! {
        // @generated by move-bindgen — do not edit by hand.
        #![allow(unused_imports, non_snake_case, non_upper_case_globals)]
        #doc_attr

        use move_bindgen_runtime::*;
        use serde::{Deserialize, Serialize};
        use std::marker::PhantomData;

        #body
    };
    let file: syn::File =
        syn::parse2(header).context("parsing generated module TokenStream as syn::File")?;
    Ok(prettyplease::unparse(&file))
}

fn render_lib_rs(modules: &[String], package_addr: AccountAddress) -> Result<String> {
    let mod_decls = modules.iter().map(|n| {
        let ident = format_ident!("{}", n);
        quote! { pub mod #ident; }
    });
    let bytes = package_addr.into_bytes();
    let byte_lits = bytes.iter().map(|b| quote!(#b));

    let lib = quote! {
        // @generated by move-bindgen — do not edit by hand.
        #![allow(unused_imports, non_snake_case, clippy::too_many_arguments)]

        use move_bindgen_runtime::Address;

        #( #mod_decls )*

        /// Address the package was generated against.
        pub const PACKAGE_ID: Address = Address::new([ #( #byte_lits ),* ]);
    };
    let file: syn::File =
        syn::parse2(lib).context("parsing generated lib.rs TokenStream as syn::File")?;
    Ok(prettyplease::unparse(&file))
}

fn render_cargo_toml(
    crate_name: &str,
    package_name: &str,
    runtime: &crate::config::RuntimeSpec,
) -> String {
    let runtime_dep = render_runtime_dep_line(runtime);
    format!(
        "# @generated by move-bindgen — regenerate with `move-bindgen generate`.\n\
         \n\
         [package]\n\
         name = \"{crate_name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\
         description = \"Generated bindings for the `{package_name}` Move package.\"\n\
         \n\
         [dependencies]\n\
         {runtime_dep}\n\
         serde = {{ version = \"1\", features = [\"derive\"] }}\n\
         bcs   = \"0.1\"\n\
         \n\
         # Detach this crate from any parent workspace it might be generated inside.\n\
         [workspace]\n",
    )
}

fn render_runtime_dep_line(spec: &crate::config::RuntimeSpec) -> String {
    use crate::config::RuntimeSpec;
    match spec {
        RuntimeSpec::Path(p) => format!("move-bindgen-runtime = {{ path = \"{}\" }}", p.display()),
        RuntimeSpec::Version(v) => format!("move-bindgen-runtime = \"{v}\""),
        RuntimeSpec::Git {
            url,
            rev,
            branch,
            tag,
        } => {
            let mut parts = vec![format!("git = \"{url}\"")];
            if let Some(r) = rev {
                parts.push(format!("rev = \"{r}\""));
            }
            if let Some(b) = branch {
                parts.push(format!("branch = \"{b}\""));
            }
            if let Some(t) = tag {
                parts.push(format!("tag = \"{t}\""));
            }
            format!("move-bindgen-runtime = {{ {} }}", parts.join(", "))
        }
    }
}
